// src/lib/smart-layout/engine.ts
//
// THE SECRET BRAIN. `import 'server-only'` makes this module throw if it
// is ever pulled into a browser bundle, so the auto-hero quality model,
// album pacing, anti-repeat rotation and style-mix rhythm never ship to
// the client. Only /api/smart-layout imports this.
//
// Generated by build_modules.mjs — byte-exact slices, with `Photo`
// retyped to the shared `LayoutPhoto` (metadata only).

import 'server-only'
import {
  TEMPLATES,
  templateFamily,
  scoreTemplateForPhotos,
} from './templates'
import type {
  AlbumType,
  EventId,
  LayoutTemplate,
  Spread,
  LayoutPhoto,
  AlbumStyle,
  LayoutFamily,
} from './templates'

// A photo must be at least this big on each edge to be featured
// full-page (so a full-bleed single never looks soft).
const HERO_MIN_PX = 3000

/** Which layout family a given spread should use.
 *  @param isHeroSpread  this spread features a hero photo
 *  @param spreadOrdinal 0-based running position across the whole album
 *
 *  Mix rhythm (0-based): spreads 0, 1, 4, 7, 10 … are full-bleed, the rest
 *  matted — so even with ZERO hero tags every album opens bold and keeps a
 *  bleed→matted→matted heartbeat instead of looking uniform. */
function familyForSpread(
  style: AlbumStyle,
  isHeroSpread: boolean,
  spreadOrdinal: number,
): LayoutFamily {
  if (style === 'clean') return 'mat'
  if (style === 'bold') return 'bleed'
  // mix
  if (isHeroSpread) return 'bleed'
  if (spreadOrdinal <= 1) return 'bleed' // bold opening
  return spreadOrdinal % 3 === 1 ? 'bleed' : 'mat'
}

function pickTemplate(
  type: AlbumType,
  count: number,
  needsHero: boolean,
  preferredId?: string,
  photos?: { width: number; height: number }[],
  spreadAspectRatio?: number,
  family?: LayoutFamily,
  /** Running spread ordinal — used to rotate between near-equally-good
   *  templates so consecutive spreads don't all reuse the SAME layout. */
  variety = 0,
  /** templateId used by the PREVIOUS spread of this photo-count. Strongly
   *  avoided so two spreads in a row never share the same layout. */
  avoidId?: string,
): LayoutTemplate | null {
  let candidates = TEMPLATES.filter(
    (t) =>
      t.compat.includes(type) &&
      t.slots.length === count &&
      (needsHero ? t.slots.some((s) => s.isHero) : !t.slots.some((s) => s.isHero)),
  )
  if (candidates.length === 0) return null

  // Narrow to the requested family (bleed vs matted) when the album mood
  // asks for it — but only if that family actually has a template for this
  // count/hero combo. Otherwise keep all candidates so a layout is never
  // dropped just because one family lacks a matching template.
  if (family) {
    const fam = candidates.filter((t) => templateFamily(t) === family)
    if (fam.length > 0) candidates = fam
  }

  // No photo info → preserve the old behaviour (preferred id, else
  // rotate through candidates so the album isn't all one layout).
  if (!photos || photos.length === 0 || spreadAspectRatio === undefined) {
    if (preferredId) {
      const pref = candidates.find((t) => t.id === preferredId)
      if (pref) return pref
    }
    // Skip the previous spread's template if we have an alternative.
    const pool =
      avoidId && candidates.length > 1
        ? candidates.filter((t) => t.id !== avoidId)
        : candidates
    return pool[((variety % pool.length) + pool.length) % pool.length]
  }

  // Orientation-aware: score every candidate by how well its slot shapes
  // match the photos' orientations (portrait vs landscape). Then:
  //  • strongly penalise the previous spread's template so the SAME layout
  //    never repeats back-to-back, and
  //  • rotate among the templates that are NEARLY as good as the best so
  //    the album keeps visual variety instead of one hammered template.
  const VARIETY_EPS = 0.06
  const scored = candidates.map((c) => ({
    t: c,
    s:
      scoreTemplateForPhotos(c, photos, spreadAspectRatio) +
      (c.id === preferredId ? 0.04 : 0) -
      // Big penalty (more than the full orientation score range) so the
      // repeated layout loses unless it's the ONLY option.
      (c.id === avoidId ? 1.5 : 0),
  }))
  scored.sort((a, b) => b.s - a.s)
  const top = scored[0].s
  const near = scored.filter((x) => x.s >= top - VARIETY_EPS)
  return near[((variety % near.length) + near.length) % near.length].t
}

// ============== AUTO-HERO SELECTION ==============
// The client should NOT have to tag hero photos. Code picks the most
// "frame-worthy" shots automatically: sharp enough to print full-page,
// good resolution, and a clean (non-extreme) aspect ratio.

/** Higher = better hero candidate. Returns -1 if the photo can't be a
 *  hero at all (too small to print sharp full-page). */
function scorePhotoForHero(p: LayoutPhoto): number {
  if (p.blurry) return -1
  if (p.width < HERO_MIN_PX || p.height < HERO_MIN_PX) return -1

  // Resolution: more pixels = sharper big print. Capped so a single
  // giant file doesn't dominate everything.
  const mp = Math.min(40, (p.width * p.height) / 1_000_000)
  let score = mp

  // Aspect: a hero takes a full page. Strong portraits and clean
  // landscapes look great big; extreme panoramas/slivers look awkward
  // as a single hero page.
  const ar = p.width / p.height
  if (ar >= 0.6 && ar <= 1.7) score += 6 // pleasing range
  else if (ar < 0.4 || ar > 2.6) score -= 8 // extreme → poor hero

  // The client explicitly liked it.
  if (p.tagged === 'favorite') score += 10
  if (p.tagged === 'hero') score += 1000 // manual heroes always win
  return score
}

// ============== LAYOUT ENGINE ==============
// Pacing rule: every 3rd spread is a hero spread (positions 2, 5, 8, ...
// 0-indexed within an event). Non-hero spreads default to PAIR (2 photos).
// Density only steps up when math requires it to fit all photos.
// Strict event grouping: each spread contains photos from ONE event.

function generateLayout(
  photos: LayoutPhoto[],
  pageCount: number,
  type: AlbumType,
  spreadAspectRatio: number,
  style: AlbumStyle = 'mix',
): Spread[] {
  const useable = photos.filter((p) => !p.blurry)
  if (useable.length === 0) return []

  // Photos are placed in CHRONOLOGICAL order (EXIF capture time →
  // filename number → upload order). We no longer pull "hero" photos
  // out of sequence — the album reads as a story, in the order the day
  // actually happened. A photo that lands on its own spread becomes a
  // full-page feature naturally; consecutive photos share orientation-
  // matched multi-photo layouts. The layout family (full-bleed vs
  // matted) still follows the per-spread mix rhythm in familyForSpread.

  const eventOrder: EventId[] = [
    'mehndi',
    'haldi',
    'prep',
    'nikkah',
    'wedding',
    'reception',
    'valima',
    'other1',
    'other2',
    // 'unassigned' is appended last so any photos the user didn't tag
    // in the Group step still get placed in the album. Without this,
    // untagged photos vanish during generation and the album ends up
    // empty (0 spreads). Per-spread label falls back gracefully when
    // the EventId isn't in the EVENTS list.
    'unassigned',
  ]
  // Establish a stable upload index for each photo so we can fall back
  // to original order when neither EXIF nor filename give us a signal.
  const uploadIndex = new Map<string, number>()
  useable.forEach((p, i) => uploadIndex.set(p.id, i))
  /** Chronological order priority: EXIF DateTimeOriginal → filename
   *  sequence → upload index. Stable: photos that have neither EXIF
   *  nor a number stay in upload order. */
  const chronoKey = (p: LayoutPhoto): [number, number, number] => [
    typeof p.capturedAt === 'number' ? p.capturedAt : Number.POSITIVE_INFINITY,
    typeof p.seqNum === 'number' ? p.seqNum : Number.POSITIVE_INFINITY,
    uploadIndex.get(p.id) ?? 0,
  ]
  const byChrono = (a: LayoutPhoto, b: LayoutPhoto) => {
    const ka = chronoKey(a)
    const kb = chronoKey(b)
    return ka[0] - kb[0] || ka[1] - kb[1] || ka[2] - kb[2]
  }

  const buckets = eventOrder
    .map((eid) => ({
      eid,
      // Sort each event's photos chronologically so the album reads as
      // a story (Mehndi morning → evening, Wedding ceremony → dance,
      // etc.) instead of upload order.
      photos: useable.filter((p) => p.eventId === eid).slice().sort(byChrono),
    }))
    .filter((b) => b.photos.length > 0)

  if (buckets.length === 0) return []

  // Allocate spread budgets per event proportional to photo count
  const totalPhotos = useable.length

  const rawBudgets = buckets.map((b) => ({
    eid: b.eid,
    bucket: b,
    spreads: Math.max(1, Math.round((b.photos.length / totalPhotos) * pageCount)),
  }))
  let total = rawBudgets.reduce((s, x) => s + x.spreads, 0)
  while (total > pageCount) {
    const biggest = rawBudgets.reduce((a, b) => (a.spreads > b.spreads ? a : b))
    biggest.spreads--
    total--
  }
  while (total < pageCount) {
    const biggest = rawBudgets.reduce((a, b) => (a.spreads > b.spreads ? a : b))
    biggest.spreads++
    total++
  }

  const spreads: Spread[] = []
  let idx = 0
  // Remember the last template used for each photo-count so the next
  // same-count spread is forced to a DIFFERENT layout (no repeats).
  const lastTplByCount: Record<number, string> = {}
  const avoidFor = (n: number) => lastTplByCount[n]
  const remember = (tplId: string, n: number) => {
    lastTplByCount[n] = tplId
  }

  for (const { eid, bucket, spreads: spreadBudget } of rawBudgets) {
    // Photos for this event, already sorted in chronological order
    // (EXIF capture time → filename number → upload order).
    const seq = bucket.photos
    const eventSpreads: Spread[] = []
    let i = 0
    let safety = 100000

    // Walk the photos in order, taking consecutive chunks for each
    // spread. Nothing is reordered — spread 1 holds the earliest
    // photos, the last spread the latest.
    while (i < seq.length && eventSpreads.length < spreadBudget && safety-- > 0) {
      const remainingPhotos = seq.length - i
      const remainingSpreads = spreadBudget - eventSpreads.length

      // Full-page feature: at a gentle cadence (every 3rd album spread),
      // give the NEXT photo its own page. Two guards:
      //   • surplus  — more photos than spreads, so we're not forcing a
      //     single where every spread already needs to be a single.
      //   • notDense — the album isn't packed tight (≤3 photos per
      //     remaining spread on average). In a dense album every spread
      //     must hold several photos, so we DON'T waste one on a single
      //     (that would push photos into the unused pool).
      // The photo keeps its chronological position and must be high-res
      // enough to print sharp full-page.
      const atFeatureCadence = idx % 3 === 2
      const surplus = remainingPhotos > remainingSpreads
      const notDense = remainingPhotos <= remainingSpreads * 3
      const featureSingle =
        atFeatureCadence && surplus && notDense && scorePhotoForHero(seq[i]) >= 0

      let chunk: LayoutPhoto[]
      if (featureSingle) {
        chunk = [seq[i]]
      } else {
        // Spread the remaining photos as evenly as possible across the
        // remaining spreads (ceil leans toward placing everything), then
        // clamp to a sensible 1–5 photos per spread.
        let size = Math.ceil(remainingPhotos / remainingSpreads)
        size = Math.max(1, Math.min(5, size))
        chunk = seq.slice(i, i + size)
      }
      i += chunk.length

      // A single-photo spread is a full-page feature. For singles we let
      // ORIENTATION pick the template (a portrait gets a tall full-page,
      // a landscape gets a wide one) instead of forcing the bleed/mat
      // rhythm — otherwise a portrait could land in a wide "panorama"
      // frame. Multi-photo spreads keep the family rhythm and are chosen
      // by how well the slot shapes match the photos' orientation
      // (portrait vs landscape) — see scoreTemplateForPhotos.
      const count = chunk.length
      const useHero = count === 1
      const family = useHero ? undefined : familyForSpread(style, false, idx)
      const tpl =
        pickTemplate(type, count, useHero, undefined, chunk, spreadAspectRatio, family, idx, avoidFor(count)) ??
        pickTemplate(type, count, useHero, undefined, chunk, spreadAspectRatio, undefined, idx, avoidFor(count)) ??
        pickTemplate(type, count, !useHero, undefined, chunk, spreadAspectRatio, undefined, idx, avoidFor(count))

      if (!tpl) {
        // Defensive: should never happen for counts 1–5. Place the photos
        // anyway with a count-appropriate fallback so none are lost.
        const fallbackId =
          count >= 5 ? 'mat-5-row' : count === 4 ? 'mat-4-grid' : count === 3 ? 'mat-3' : count === 2 ? 'pair' : 'one-full'
        eventSpreads.push({ id: `s-${idx++}`, templateId: fallbackId, photoIds: chunk.map((p) => p.id), eventId: eid })
        continue
      }
      eventSpreads.push({ id: `s-${idx++}`, templateId: tpl.id, photoIds: chunk.map((p) => p.id), eventId: eid })
      remember(tpl.id, tpl.slots.length)
    }

    // If we hit the spread budget but still have photos in this event,
    // jam the remainder onto the last spread (up to the 5-photo cap) so
    // every photo is placed. Anything beyond that falls to the unused
    // pool (the client can drop it onto any spread).
    if (i < seq.length && eventSpreads.length > 0) {
      const leftover = seq.slice(i)
      const last = eventSpreads[eventSpreads.length - 1]
      const tgt = Math.min(5, last.photoIds.length + leftover.length)
      const upgrade = pickTemplate(
        type, tgt, false, undefined, undefined, undefined,
        templateFamily({ id: last.templateId }), idx,
      )
      if (upgrade) {
        last.templateId = upgrade.id
        last.photoIds = [
          ...last.photoIds,
          ...leftover.slice(0, tgt - last.photoIds.length).map((p) => p.id),
        ]
      }
    }

    spreads.push(...eventSpreads)
  }

  // Final orphan-safety pass
  const placed = new Set(spreads.flatMap((s) => s.photoIds).filter((id): id is string => Boolean(id)))
  const orphans = useable.filter((p) => !placed.has(p.id))
  if (orphans.length > 0 && spreads.length > 0) {
    const last = spreads[spreads.length - 1]
    const tgt = Math.min(5, last.photoIds.length + orphans.length)
    const upgrade = pickTemplate(
      type, tgt, false, undefined, undefined, undefined,
      templateFamily({ id: last.templateId }),
    )
    if (upgrade) {
      last.templateId = upgrade.id
      last.photoIds = [...last.photoIds, ...orphans.slice(0, tgt - last.photoIds.length).map((p) => p.id)]
    }
  }

  return spreads
}

export { generateLayout }
export type { AlbumStyle }
