// src/lib/smart-layout/engine.ts
//
// THE SECRET BRAIN. `import 'server-only'` makes this module throw if it
// is ever pulled into a browser bundle, so the auto-hero quality model,
// album pacing, anti-repeat rotation and style-mix rhythm never ship to
// the client. Only /api/smart-layout imports this.
//
// Generated by build_modules.mjs — byte-exact slices, with `Photo`
// retyped to the shared `LayoutPhoto` (metadata only).

import 'server-only'
import {
  TEMPLATES,
  templateFamily,
  scoreTemplateForPhotos,
} from './templates'
import type {
  AlbumType,
  EventId,
  LayoutTemplate,
  Spread,
  LayoutPhoto,
  AlbumStyle,
  LayoutFamily,
} from './templates'

const HERO_MIN_PX = 3000
const HERO_CAP = 8
const HERO_AUTO_EVERY = 4
const HERO_AUTO_MIN = 2

/** Which layout family a given spread should use.
 *  @param isHeroSpread  this spread features a hero photo
 *  @param spreadOrdinal 0-based running position across the whole album
 *
 *  Mix rhythm (0-based): spreads 0, 1, 4, 7, 10 … are full-bleed, the rest
 *  matted — so even with ZERO hero tags every album opens bold and keeps a
 *  bleed→matted→matted heartbeat instead of looking uniform. */
function familyForSpread(
  style: AlbumStyle,
  isHeroSpread: boolean,
  spreadOrdinal: number,
): LayoutFamily {
  if (style === 'clean') return 'mat'
  if (style === 'bold') return 'bleed'
  // mix
  if (isHeroSpread) return 'bleed'
  if (spreadOrdinal <= 1) return 'bleed' // bold opening
  return spreadOrdinal % 3 === 1 ? 'bleed' : 'mat'
}

function pickTemplate(
  type: AlbumType,
  count: number,
  needsHero: boolean,
  preferredId?: string,
  photos?: { width: number; height: number }[],
  spreadAspectRatio?: number,
  family?: LayoutFamily,
  /** Running spread ordinal — used to rotate between near-equally-good
   *  templates so consecutive spreads don't all reuse the SAME layout. */
  variety = 0,
  /** templateId used by the PREVIOUS spread of this photo-count. Strongly
   *  avoided so two spreads in a row never share the same layout. */
  avoidId?: string,
): LayoutTemplate | null {
  let candidates = TEMPLATES.filter(
    (t) =>
      t.compat.includes(type) &&
      t.slots.length === count &&
      (needsHero ? t.slots.some((s) => s.isHero) : !t.slots.some((s) => s.isHero)),
  )
  if (candidates.length === 0) return null

  // Narrow to the requested family (bleed vs matted) when the album mood
  // asks for it — but only if that family actually has a template for this
  // count/hero combo. Otherwise keep all candidates so a layout is never
  // dropped just because one family lacks a matching template.
  if (family) {
    const fam = candidates.filter((t) => templateFamily(t) === family)
    if (fam.length > 0) candidates = fam
  }

  // No photo info → preserve the old behaviour (preferred id, else
  // rotate through candidates so the album isn't all one layout).
  if (!photos || photos.length === 0 || spreadAspectRatio === undefined) {
    if (preferredId) {
      const pref = candidates.find((t) => t.id === preferredId)
      if (pref) return pref
    }
    // Skip the previous spread's template if we have an alternative.
    const pool =
      avoidId && candidates.length > 1
        ? candidates.filter((t) => t.id !== avoidId)
        : candidates
    return pool[((variety % pool.length) + pool.length) % pool.length]
  }

  // Orientation-aware: score every candidate by how well its slot shapes
  // match the photos' orientations (portrait vs landscape). Then:
  //  • strongly penalise the previous spread's template so the SAME layout
  //    never repeats back-to-back, and
  //  • rotate among the templates that are NEARLY as good as the best so
  //    the album keeps visual variety instead of one hammered template.
  const VARIETY_EPS = 0.06
  const scored = candidates.map((c) => ({
    t: c,
    s:
      scoreTemplateForPhotos(c, photos, spreadAspectRatio) +
      (c.id === preferredId ? 0.04 : 0) -
      // Big penalty (more than the full orientation score range) so the
      // repeated layout loses unless it's the ONLY option.
      (c.id === avoidId ? 1.5 : 0),
  }))
  scored.sort((a, b) => b.s - a.s)
  const top = scored[0].s
  const near = scored.filter((x) => x.s >= top - VARIETY_EPS)
  return near[((variety % near.length) + near.length) % near.length].t
}

// ============== AUTO-HERO SELECTION ==============
// The client should NOT have to tag hero photos. Code picks the most
// "frame-worthy" shots automatically: sharp enough to print full-page,
// good resolution, and a clean (non-extreme) aspect ratio.

/** Higher = better hero candidate. Returns -1 if the photo can't be a
 *  hero at all (too small to print sharp full-page). */
function scorePhotoForHero(p: LayoutPhoto): number {
  if (p.blurry) return -1
  if (p.width < HERO_MIN_PX || p.height < HERO_MIN_PX) return -1

  // Resolution: more pixels = sharper big print. Capped so a single
  // giant file doesn't dominate everything.
  const mp = Math.min(40, (p.width * p.height) / 1_000_000)
  let score = mp

  // Aspect: a hero takes a full page. Strong portraits and clean
  // landscapes look great big; extreme panoramas/slivers look awkward
  // as a single hero page.
  const ar = p.width / p.height
  if (ar >= 0.6 && ar <= 1.7) score += 6 // pleasing range
  else if (ar < 0.4 || ar > 2.6) score -= 8 // extreme → poor hero

  // The client explicitly liked it.
  if (p.tagged === 'favorite') score += 10
  if (p.tagged === 'hero') score += 1000 // manual heroes always win
  return score
}

/**
 * Pick which photo ids should be heroes. Honours any the client manually
 * tagged, then auto-promotes the best remaining shots until the album has
 * a healthy hero cadence (≈ one per HERO_AUTO_EVERY photos, at least
 * HERO_AUTO_MIN, never more than HERO_CAP).
 */
function autoSelectHeroIds(useable: LayoutPhoto[]): Set<string> {
  const tagged = useable.filter((p) => p.tagged === 'hero')
  const heroIds = new Set<string>(tagged.map((p) => p.id))

  const target = Math.min(
    HERO_CAP,
    Math.max(HERO_AUTO_MIN, Math.round(useable.length / HERO_AUTO_EVERY)),
  )
  if (heroIds.size >= target) return heroIds

  const eligible = useable
    .filter((p) => !heroIds.has(p.id) && scorePhotoForHero(p) >= 0)
    .map((p) => ({ p, s: scorePhotoForHero(p) }))
    .sort((a, b) => b.s - a.s)

  for (const { p } of eligible) {
    if (heroIds.size >= target) break
    heroIds.add(p.id)
  }
  return heroIds
}

// ============== LAYOUT ENGINE ==============
// Pacing rule: every 3rd spread is a hero spread (positions 2, 5, 8, ...
// 0-indexed within an event). Non-hero spreads default to PAIR (2 photos).
// Density only steps up when math requires it to fit all photos.
// Strict event grouping: each spread contains photos from ONE event.

function generateLayout(
  photos: LayoutPhoto[],
  pageCount: number,
  type: AlbumType,
  spreadAspectRatio: number,
  style: AlbumStyle = 'mix',
): Spread[] {
  const useable = photos.filter((p) => !p.blurry)
  if (useable.length === 0) return []

  // Auto-pick hero photos so the client never has to tag them. Includes
  // any they DID tag, plus the best remaining shots up to a healthy
  // cadence. The whole album shares one set so heroes land on the
  // genuinely strongest images regardless of event.
  const heroIds = autoSelectHeroIds(useable)

  // The layout family is decided PER SPREAD using the running spread
  // ordinal `idx` (see familyForSpread) so the mix rhythm works even when
  // the client tagged zero hero photos.

  const eventOrder: EventId[] = [
    'mehndi',
    'haldi',
    'prep',
    'nikkah',
    'wedding',
    'reception',
    'valima',
    'other1',
    'other2',
    // 'unassigned' is appended last so any photos the user didn't tag
    // in the Group step still get placed in the album. Without this,
    // untagged photos vanish during generation and the album ends up
    // empty (0 spreads). Per-spread label falls back gracefully when
    // the EventId isn't in the EVENTS list.
    'unassigned',
  ]
  const buckets = eventOrder
    .map((eid) => ({
      eid,
      photos: useable.filter((p) => p.eventId === eid),
    }))
    .filter((b) => b.photos.length > 0)

  if (buckets.length === 0) return []

  // Allocate spread budgets per event proportional to photo count
  const totalPhotos = useable.length

  const rawBudgets = buckets.map((b) => ({
    eid: b.eid,
    bucket: b,
    spreads: Math.max(1, Math.round((b.photos.length / totalPhotos) * pageCount)),
  }))
  let total = rawBudgets.reduce((s, x) => s + x.spreads, 0)
  while (total > pageCount) {
    const biggest = rawBudgets.reduce((a, b) => (a.spreads > b.spreads ? a : b))
    biggest.spreads--
    total--
  }
  while (total < pageCount) {
    const biggest = rawBudgets.reduce((a, b) => (a.spreads > b.spreads ? a : b))
    biggest.spreads++
    total++
  }

  const spreads: Spread[] = []
  let idx = 0
  // Guarantee at least one DUAL-HERO spread per album (two big heroes side
  // by side on the same spread) when the album has ≥2 heroes total.
  let doubleHeroPlaced = false
  const totalHeroes = useable.filter((p) => heroIds.has(p.id)).length
  // Remember the last template used for each photo-count so the next
  // same-count spread is forced to a DIFFERENT layout (no repeats).
  const lastTplByCount: Record<number, string> = {}
  const avoidFor = (n: number) => lastTplByCount[n]
  const remember = (tplId: string, n: number) => {
    lastTplByCount[n] = tplId
  }

  for (const { eid, bucket, spreads: spreadBudget } of rawBudgets) {
    // Heroes = anything in the auto-selected hero set (manual + auto).
    // Best heroes first so the most striking shots get featured.
    const heroes = bucket.photos
      .filter((p) => heroIds.has(p.id))
      .sort((a, b) => scorePhotoForHero(b) - scorePhotoForHero(a))
    const favorites = bucket.photos.filter(
      (p) => p.tagged === 'favorite' && !heroIds.has(p.id),
    )
    const others = bucket.photos.filter(
      (p) => p.tagged === 'none' && !heroIds.has(p.id),
    )
    const totalEventPhotos = bucket.photos.length

    // ---- PASS 1: PLAN ----
    // Decide which spread positions are heroes vs non-hero, and the
    // photo count per spread.
    const isHeroSpot: boolean[] = new Array(spreadBudget).fill(false)
    let heroAssigned = 0
    // First pass: every 3rd position (i % 3 === 2)
    for (let i = 0; i < spreadBudget; i++) {
      if (heroAssigned >= heroes.length) break
      if (i % 3 === 2) {
        isHeroSpot[i] = true
        heroAssigned++
      }
    }
    // If extra heroes still remain, append on first available pair slots
    // from the front (so heroes get featured even if we have many).
    for (let i = 0; i < spreadBudget && heroAssigned < heroes.length; i++) {
      if (!isHeroSpot[i]) {
        isHeroSpot[i] = true
        heroAssigned++
      }
    }

    const heroSpreadCount = isHeroSpot.filter(Boolean).length
    const pairSpreadCount = spreadBudget - heroSpreadCount

    // LayoutPhoto budget: heroes themselves are placed (heroSpreadCount of them),
    // plus the non-hero photos to be distributed.
    const nonHeroPhotos = favorites.length + others.length

    // Per-spread sizes: hero spread defaults to 2 photos (hero+1, matches
    // pair density). Pair spread defaults to 2.
    const sizes: number[] = isHeroSpot.map((isH) => (isH ? 2 : 2))

    // Adjust sizes to fit ALL non-hero photos.
    // Non-hero photos to place = nonHeroPhotos
    // Slots dedicated to non-hero = (heroSpreadCount * 1 fillers) + (pairSpreadCount * 2)
    let nonHeroSlotsPlanned = heroSpreadCount * 1 + pairSpreadCount * 2

    if (nonHeroSlotsPlanned > nonHeroPhotos) {
      // Slots > photos. Reduce some pair spreads from 2 to 1 photo.
      let surplus = nonHeroSlotsPlanned - nonHeroPhotos
      for (let i = sizes.length - 1; i >= 0 && surplus > 0; i--) {
        if (!isHeroSpot[i] && sizes[i] > 1) {
          sizes[i]--
          surplus--
        }
      }
      // If still surplus, reduce pair spreads to 0 (shouldn't normally happen)
      for (let i = sizes.length - 1; i >= 0 && surplus > 0; i--) {
        if (!isHeroSpot[i] && sizes[i] > 0) {
          sizes[i]--
          surplus--
        }
      }
    } else if (nonHeroSlotsPlanned < nonHeroPhotos) {
      // Need to increase density. Step up hero spreads first (hero+1 → hero+2 → +3 → +4 max),
      // then pair spreads (2 → 3 → 4 → 5). Hard cap is 5 photos per spread — anything
      // beyond that becomes unused-pool overflow.
      let deficit = nonHeroPhotos - nonHeroSlotsPlanned
      const heroMax = 5 // 1 hero + 4 fillers
      const pairMax = 5
      let safety = 1000
      while (deficit > 0 && safety-- > 0) {
        let bumped = false
        // Bump hero spreads first (give heroes more support photos)
        for (let i = 0; i < sizes.length && deficit > 0; i++) {
          if (isHeroSpot[i] && sizes[i] < heroMax) {
            sizes[i]++
            deficit--
            bumped = true
          }
        }
        // Then bump pair spreads
        for (let i = 0; i < sizes.length && deficit > 0; i++) {
          if (!isHeroSpot[i] && sizes[i] < pairMax) {
            sizes[i]++
            deficit--
            bumped = true
          }
        }
        if (!bumped) break
      }
    }

    // ---- PASS 2: ASSIGN ----
    // Build the actual spreads using the planned sizes + hero positions.
    const fillerQueue: LayoutPhoto[] = [...favorites, ...others]
    let alternateLeft = true
    const eventSpreads: Spread[] = []

    for (let i = 0; i < spreadBudget; i++) {
      if (isHeroSpot[i]) {
        // DUAL-HERO: once per album, give two of the best heroes their own
        // shared spread (two big photos, no fillers) for maximum impact.
        if (!doubleHeroPlaced && totalHeroes >= 2 && heroes.length >= 2) {
          const h1 = heroes.shift()!
          const h2 = heroes.shift()!
          const duo = [h1, h2]
          const dualTpl =
            pickTemplate(type, 2, false, undefined, duo, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(2)) ??
            pickTemplate(type, 2, true, undefined, duo, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(2))
          if (dualTpl) {
            eventSpreads.push({
              id: `s-${idx++}`,
              templateId: dualTpl.id,
              photoIds: duo.map((p) => p.id),
              eventId: eid,
            })
            remember(dualTpl.id, 2)
            doubleHeroPlaced = true
            continue
          }
          // Couldn't find a 2-slot template — put them back, fall through.
          heroes.unshift(h1, h2)
        }
        const hero = heroes.shift()
        if (!hero) {
          // Shouldn't happen — but if it does, fall back to a pair
          const take = Math.min(sizes[i], fillerQueue.length)
          const chunk = fillerQueue.splice(0, take)
          if (chunk.length === 0) continue
          const tpl =
            pickTemplate(type, chunk.length, false, undefined, chunk, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(chunk.length)) ??
            pickTemplate(type, chunk.length, true, undefined, chunk, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(chunk.length))
          if (!tpl) continue
          eventSpreads.push({ id: `s-${idx++}`, templateId: tpl.id, photoIds: chunk.map((p) => p.id), eventId: eid })
          remember(tpl.id, tpl.slots.length)
          continue
        }
        const fillerCount = Math.max(0, sizes[i] - 1)
        const fillers = fillerQueue.splice(0, fillerCount)
        const total = 1 + fillers.length
        // Pick template: hero+N with side alternating
        const tplId = alternateLeft
          ? total === 5 ? 'hero-4r' : total === 4 ? 'hero-3r' : total === 3 ? 'hero-2r' : 'hero-1r'
          : total === 5 ? 'hero-4l' : total === 4 ? 'hero-3l' : total === 3 ? 'hero-2l' : 'hero-1l'
        const heroPhotos = [hero, ...fillers]
        const tpl =
          pickTemplate(type, total, true, tplId, heroPhotos, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(total)) ??
          pickTemplate(type, total, true, undefined, heroPhotos, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(total))
        if (!tpl) {
          // Fall back: put hero into a 2-photo pair as if it were any photo
          const fallback = pickTemplate(type, total, false, undefined, heroPhotos, spreadAspectRatio, familyForSpread(style, true, idx), idx, avoidFor(total))
          if (!fallback) continue
          eventSpreads.push({
            id: `s-${idx++}`,
            templateId: fallback.id,
            photoIds: [hero, ...fillers].map((p) => p.id),
            eventId: eid,
          })
          remember(fallback.id, fallback.slots.length)
          continue
        }
        const heroSlotIdx = tpl.slots.findIndex((s) => s.isHero)
        const photoIds: string[] = new Array(tpl.slots.length).fill('')
        photoIds[heroSlotIdx] = hero.id
        let fi = 0
        for (let s = 0; s < tpl.slots.length; s++) {
          if (s === heroSlotIdx) continue
          if (fillers[fi]) photoIds[s] = fillers[fi++].id
        }
        eventSpreads.push({ id: `s-${idx++}`, templateId: tpl.id, photoIds: photoIds.filter(Boolean), eventId: eid })
        remember(tpl.id, tpl.slots.length)
        alternateLeft = !alternateLeft
      } else {
        // Pair (or higher density) spread
        const take = Math.min(sizes[i], fillerQueue.length)
        if (take === 0) continue
        const chunk = fillerQueue.splice(0, take)
        const tpl =
          pickTemplate(type, chunk.length, false, undefined, chunk, spreadAspectRatio, familyForSpread(style, false, idx), idx, avoidFor(chunk.length)) ??
          pickTemplate(type, chunk.length, true, undefined, chunk, spreadAspectRatio, familyForSpread(style, false, idx), idx, avoidFor(chunk.length))
        if (!tpl) continue
        eventSpreads.push({ id: `s-${idx++}`, templateId: tpl.id, photoIds: chunk.map((p) => p.id), eventId: eid })
        remember(tpl.id, tpl.slots.length)
      }
    }

    // If anything still remains in this event, jam it onto the last spread
    // by upgrading the template — keeps the all-photos-placed promise.
    const stillLeft = [...heroes, ...fillerQueue]
    if (stillLeft.length > 0 && eventSpreads.length > 0) {
      const last = eventSpreads[eventSpreads.length - 1]
      const tgt = Math.min(5, last.photoIds.length + stillLeft.length)
      const upgrade = pickTemplate(
        type, tgt, false, undefined, undefined, undefined,
        templateFamily({ id: last.templateId }), idx,
      )
      if (upgrade) {
        last.templateId = upgrade.id
        last.photoIds = [
          ...last.photoIds,
          ...stillLeft.slice(0, tgt - last.photoIds.length).map((p) => p.id),
        ]
      }
    }

    spreads.push(...eventSpreads)
  }

  // Final orphan-safety pass
  const placed = new Set(spreads.flatMap((s) => s.photoIds).filter((id): id is string => Boolean(id)))
  const orphans = useable.filter((p) => !placed.has(p.id))
  if (orphans.length > 0 && spreads.length > 0) {
    const last = spreads[spreads.length - 1]
    const tgt = Math.min(5, last.photoIds.length + orphans.length)
    const upgrade = pickTemplate(
      type, tgt, false, undefined, undefined, undefined,
      templateFamily({ id: last.templateId }),
    )
    if (upgrade) {
      last.templateId = upgrade.id
      last.photoIds = [...last.photoIds, ...orphans.slice(0, tgt - last.photoIds.length).map((p) => p.id)]
    }
  }

  return spreads
}

export { generateLayout }
export type { AlbumStyle }
