// src/lib/smart-layout/templates.ts
//
// SHARED layout data + geometry. Imported by BOTH the browser (to draw
// spreads, power the picker, thumbnails) and the server engine. The slot
// rectangles are visible in the rendered DOM anyway, so they live here;
// the *decision* logic (which template, which heroes, pacing) is the
// secret part and lives ONLY in engine.ts (server-side).
//
// Generated by build_modules.mjs — byte-exact slices from page.tsx.

type AlbumType = 'standard' | 'layflat'

type EventId =
  | 'unassigned'
  | 'mehndi'
  | 'haldi'
  | 'prep'
  | 'nikkah'
  | 'wedding'
  | 'reception'
  | 'valima'
  | 'other1'
  | 'other2'
  // Legacy values from older saved albums — kept in the union so
  // hydration doesn't trip on them. migrateLegacyEvent maps these
  // to current EventIds.
  | 'ceremony'
  | 'portraits'
  | 'other'

type Slot = { x: number; y: number; w: number; h: number; isHero?: boolean }

type LayoutTemplate = {
  id: string
  name: string
  slots: Slot[]
  compat: AlbumType[]
}

type Spread = {
  id: string
  templateId: string
  // (string | null)[] so a slot can be empty after layout-grow / remove.
  // Empty slots show a "+ Add" button — the engine never inserts nulls
  // automatically, only the user does via the layout-switch flow.
  photoIds: (string | null)[]
  eventId: EventId
}

/** Minimal photo shape the layout engine needs (no preview blob). */
export type LayoutPhoto = {
  id: string
  width: number
  height: number
  tagged: 'hero' | 'favorite' | 'none'
  blurry: boolean
  eventId: EventId
  /** EXIF DateTimeOriginal (ms since epoch). Engine sorts each event's
   *  photos by this so the album reads chronologically. */
  capturedAt?: number
  /** Largest digit run in the original filename (e.g. IMG_0123.jpg).
   *  Used as a fallback when EXIF is missing. */
  seqNum?: number
}

// The single "mood" the client picks once (right after upload). The engine
// turns this into a per-spread family decision so a non-designer never has
// to think about "full bleed vs matted" per page.
//   clean → every spread matted (calm, white space, elegant)
//   bold  → every spread full-bleed (edge-to-edge, immersive, dramatic)
//   mix   → designed rhythm by spread POSITION (not hero tags, which an
//           innocent client never sets): the opening spread and then a
//           recurring beat go full-bleed for drama; the rest are matted so
//           the album breathes. Hero spreads are always full-bleed too.
type AlbumStyle = 'clean' | 'bold' | 'mix'

/** Two layout families: 'mat' = floats photos in negative space (a
 *  colour / blurred-photo background shows around them); 'bleed' =
 *  edge-to-edge classic layouts. Matted templates are all id 'mat-*'. */
type LayoutFamily = 'bleed' | 'mat'
function templateFamily(t: { id: string }): LayoutFamily {
  return t.id.startsWith('mat-') ? 'mat' : 'bleed'
}

/**
 * Snap a FULL-BLEED template's slots to be genuinely edge-to-edge.
 *
 * The hand-authored bleed templates have ~0.5% outer margins and ~1%
 * gaps between slots — on a real spread that's a ~10px WHITE line of the
 * page showing through. Full bleed must mean no gaps. Rather than
 * hand-fixing ~40 templates, we close every gap mathematically:
 *
 * For each slot edge, find the nearest neighbouring slot edge that
 * overlaps on the other axis; move this edge to the midpoint of the gap
 * (so two neighbours meet exactly on a shared line). If there's no
 * neighbour on that side, snap to the page edge (0 or 100). Adjacent
 * slots end up sharing an exact boundary → combined with the +1px CSS
 * overlap there is zero white. mat-* templates are returned unchanged
 * (their negative space is intentional).
 */
function bleedFillSlots(slots: Slot[]): Slot[] {
  // Two intervals overlap if they share more than a hair of length.
  const overlaps = (a0: number, a1: number, b0: number, b1: number) =>
    Math.min(a1, b1) - Math.max(a0, b0) > 0.5

  return slots.map((s) => {
    const sx0 = s.x
    const sx1 = s.x + s.w
    const sy0 = s.y
    const sy1 = s.y + s.h

    let left = 0
    let right = 100
    let top = 0
    let bottom = 100

    for (const o of slots) {
      if (o === s) continue
      const ox0 = o.x
      const ox1 = o.x + o.w
      const oy0 = o.y
      const oy1 = o.y + o.h

      // Horizontal neighbours must overlap vertically.
      if (overlaps(sy0, sy1, oy0, oy1)) {
        if (ox1 <= sx0 + 0.5) left = Math.max(left, (sx0 + ox1) / 2)
        if (ox0 >= sx1 - 0.5) right = Math.min(right, (sx1 + ox0) / 2)
      }
      // Vertical neighbours must overlap horizontally.
      if (overlaps(sx0, sx1, ox0, ox1)) {
        if (oy1 <= sy0 + 0.5) top = Math.max(top, (sy0 + oy1) / 2)
        if (oy0 >= sy1 - 0.5) bottom = Math.min(bottom, (sy1 + oy0) / 2)
      }
    }

    return {
      ...s,
      x: left,
      y: top,
      w: Math.max(1, right - left),
      h: Math.max(1, bottom - top),
    }
  })
}

/** Slots to actually RENDER: bleed → snapped edge-to-edge; mat → as-is. */
function renderSlots(t: LayoutTemplate): Slot[] {
  return templateFamily(t) === 'bleed' ? bleedFillSlots(t.slots) : t.slots
}

/* ─── Orientation-aware scoring (Part B) ────────────────────────────────
 *
 * The original engine picked candidates[0] — purely by photo count. That
 * dumped tall portrait photos into wide landscape slots and vice-versa.
 *
 * Now: classify every photo and every slot as portrait / landscape /
 * square, then score how well a template's slot shapes match the actual
 * photos going into it. A slot's TRUE shape depends on the spread's wide
 * aspect ratio (24/17 or 30/20), so a "half page" slot is actually
 * portrait-ish, and a half-height band is landscape.
 */

type AspectClass = 'portrait' | 'landscape' | 'square'

function classifyAspect(ratio: number): AspectClass {
  if (!Number.isFinite(ratio) || ratio <= 0) return 'square'
  if (ratio < 0.85) return 'portrait'
  if (ratio > 1.18) return 'landscape'
  return 'square'
}

function photoAspectClass(p: { width: number; height: number }): AspectClass {
  if (!p.width || !p.height) return 'square'
  return classifyAspect(p.width / p.height)
}

function slotAspectClass(
  slot: { w: number; h: number },
  spreadAspectRatio: number,
): AspectClass {
  if (!slot.w || !slot.h) return 'square'
  // pixel aspect = (slot.w / slot.h) × (spreadW / spreadH)
  return classifyAspect((slot.w / slot.h) * spreadAspectRatio)
}

/**
 * 0..1 — how well this template's slots fit these photos by orientation.
 * Exact class matches are worth most; square acts as a flexible wildcard.
 */
function scoreTemplateForPhotos(
  tpl: LayoutTemplate,
  photos: { width: number; height: number }[],
  spreadAspectRatio: number,
): number {
  if (tpl.slots.length === 0) return 0
  const slotCounts = { portrait: 0, landscape: 0, square: 0 }
  for (const s of tpl.slots) slotCounts[slotAspectClass(s, spreadAspectRatio)]++
  const photoCounts = { portrait: 0, landscape: 0, square: 0 }
  for (const p of photos) photoCounts[photoAspectClass(p)]++

  const pMatch = Math.min(slotCounts.portrait, photoCounts.portrait)
  const lMatch = Math.min(slotCounts.landscape, photoCounts.landscape)
  let score = (pMatch + lMatch) * 2

  // Whatever's left over — square slots take any photo, square photos
  // fit any slot — counts as a soft (half-value) match.
  const slotsLeft =
    slotCounts.portrait - pMatch + (slotCounts.landscape - lMatch) + slotCounts.square
  const photosLeft =
    photoCounts.portrait - pMatch + (photoCounts.landscape - lMatch) + photoCounts.square
  score += Math.min(slotsLeft, photosLeft) * 1

  return score / (tpl.slots.length * 2)
}

const TEMPLATES: LayoutTemplate[] = [
  // --- 2 PHOTOS ---
  {
    id: 'hero-1r',
    name: 'Hero · Solo right',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 49, h: 99 },
    ],
  },
  {
    id: 'hero-1l',
    name: 'Hero · Solo left',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99 },
      { x: 50.5, y: 0.5, w: 49, h: 99, isHero: true },
    ],
  },
  {
    id: 'pair',
    name: '2 photos',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99 },
      { x: 50.5, y: 0.5, w: 49, h: 99 },
    ],
  },

  // --- 3 PHOTOS ---
  {
    id: 'hero-2r',
    name: 'Hero · Pair right',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 49, h: 49 },
      { x: 50.5, y: 50, w: 49, h: 49.5 },
    ],
  },
  {
    id: 'hero-2l',
    name: 'Hero · Pair left',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 49 },
      { x: 0.5, y: 50, w: 49, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 99, isHero: true },
    ],
  },
  {
    id: 'pair-solo',
    name: '3 · 2+1',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 49 },
      { x: 0.5, y: 50, w: 49, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 99 },
    ],
  },

  // --- 4 PHOTOS ---
  {
    id: 'hero-3r',
    name: 'Hero · Trio right',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 49, h: 32.5 },
      { x: 50.5, y: 33.5, w: 49, h: 32.5 },
      { x: 50.5, y: 66.5, w: 49, h: 33 },
    ],
  },
  {
    id: 'hero-3l',
    name: 'Hero · Trio left',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 32.5 },
      { x: 0.5, y: 33.5, w: 49, h: 32.5 },
      { x: 0.5, y: 66.5, w: 49, h: 33 },
      { x: 50.5, y: 0.5, w: 49, h: 99, isHero: true },
    ],
  },
  {
    id: 'pair-pair',
    name: '4 · 2+2 grid',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 49 },
      { x: 0.5, y: 50, w: 49, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 49 },
      { x: 50.5, y: 50, w: 49, h: 49.5 },
    ],
  },

  // --- 5 PHOTOS ---
  {
    id: 'hero-4r',
    name: 'Hero · Quad right',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 24.25, h: 49 },
      { x: 75.25, y: 0.5, w: 24.25, h: 49 },
      { x: 50.5, y: 50, w: 24.25, h: 49.5 },
      { x: 75.25, y: 50, w: 24.25, h: 49.5 },
    ],
  },
  {
    id: 'hero-4l',
    name: 'Hero · Quad left',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24.25, h: 49 },
      { x: 25.25, y: 0.5, w: 24.25, h: 49 },
      { x: 0.5, y: 50, w: 24.25, h: 49.5 },
      { x: 25.25, y: 50, w: 24.25, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 99, isHero: true },
    ],
  },
  {
    id: 'trio-pair',
    name: '5 · 3+2',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 32.5 },
      { x: 0.5, y: 33.5, w: 49, h: 32.5 },
      { x: 0.5, y: 66.5, w: 49, h: 33 },
      { x: 50.5, y: 0.5, w: 49, h: 49 },
      { x: 50.5, y: 50, w: 49, h: 49.5 },
    ],
  },
  {
    id: 'pair-trio',
    name: '5 · 2+3',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 49 },
      { x: 0.5, y: 50, w: 49, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 32.5 },
      { x: 50.5, y: 33.5, w: 49, h: 32.5 },
      { x: 50.5, y: 66.5, w: 49, h: 33 },
    ],
  },

  // --- 6 PHOTOS ---
  {
    id: 'trio-trio',
    name: '6 · 3+3 rows',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 32.5 },
      { x: 0.5, y: 33.5, w: 49, h: 32.5 },
      { x: 0.5, y: 66.5, w: 49, h: 33 },
      { x: 50.5, y: 0.5, w: 49, h: 32.5 },
      { x: 50.5, y: 33.5, w: 49, h: 32.5 },
      { x: 50.5, y: 66.5, w: 49, h: 33 },
    ],
  },
  {
    id: 'pair-quad',
    name: '6 · 2+4',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 49 },
      { x: 0.5, y: 50, w: 49, h: 49.5 },
      { x: 50.5, y: 0.5, w: 24.25, h: 49 },
      { x: 75.25, y: 0.5, w: 24.25, h: 49 },
      { x: 50.5, y: 50, w: 24.25, h: 49.5 },
      { x: 75.25, y: 50, w: 24.25, h: 49.5 },
    ],
  },
  {
    id: 'quad-pair',
    name: '6 · 4+2',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24.25, h: 49 },
      { x: 25.25, y: 0.5, w: 24.25, h: 49 },
      { x: 0.5, y: 50, w: 24.25, h: 49.5 },
      { x: 25.25, y: 50, w: 24.25, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 49 },
      { x: 50.5, y: 50, w: 49, h: 49.5 },
    ],
  },

  // --- 7 PHOTOS ---
  {
    id: 'quad-trio',
    name: '7 · 4+3',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24.25, h: 49 },
      { x: 25.25, y: 0.5, w: 24.25, h: 49 },
      { x: 0.5, y: 50, w: 24.25, h: 49.5 },
      { x: 25.25, y: 50, w: 24.25, h: 49.5 },
      { x: 50.5, y: 0.5, w: 49, h: 32.5 },
      { x: 50.5, y: 33.5, w: 49, h: 32.5 },
      { x: 50.5, y: 66.5, w: 49, h: 33 },
    ],
  },
  {
    id: 'trio-quad',
    name: '7 · 3+4',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 32.5 },
      { x: 0.5, y: 33.5, w: 49, h: 32.5 },
      { x: 0.5, y: 66.5, w: 49, h: 33 },
      { x: 50.5, y: 0.5, w: 24.25, h: 49 },
      { x: 75.25, y: 0.5, w: 24.25, h: 49 },
      { x: 50.5, y: 50, w: 24.25, h: 49.5 },
      { x: 75.25, y: 50, w: 24.25, h: 49.5 },
    ],
  },

  // --- 8 PHOTOS ---
  {
    id: 'quad-quad',
    name: '8 · 4+4 grid',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24.25, h: 49 },
      { x: 25.25, y: 0.5, w: 24.25, h: 49 },
      { x: 0.5, y: 50, w: 24.25, h: 49.5 },
      { x: 25.25, y: 50, w: 24.25, h: 49.5 },
      { x: 50.5, y: 0.5, w: 24.25, h: 49 },
      { x: 75.25, y: 0.5, w: 24.25, h: 49 },
      { x: 50.5, y: 50, w: 24.25, h: 49.5 },
      { x: 75.25, y: 50, w: 24.25, h: 49.5 },
    ],
  },

  // --- PORTRAIT-COLUMN VARIANTS (Part A) ---
  // The original library was almost entirely landscape/grid. These
  // column layouts give the orientation scorer real choices when a
  // spread's photos are vertical (the common wedding-portrait case).

  // 3 PHOTOS — all-portrait: 1 tall + 2 tall columns
  {
    id: 'tri-cols-r',
    name: '3 · tall columns (R)',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 24, h: 99 },
      { x: 75, y: 0.5, w: 24.5, h: 99 },
    ],
  },
  {
    id: 'tri-cols-l',
    name: '3 · tall columns (L)',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24, h: 99 },
      { x: 25, y: 0.5, w: 24.5, h: 99 },
      { x: 50.5, y: 0.5, w: 49, h: 99, isHero: true },
    ],
  },
  // 4 PHOTOS — all-portrait: 4 tall columns (2 per page)
  {
    id: 'quad-cols',
    name: '4 · tall columns',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24, h: 99 },
      { x: 25, y: 0.5, w: 24.5, h: 99 },
      { x: 50.5, y: 0.5, w: 24, h: 99 },
      { x: 75, y: 0.5, w: 24.5, h: 99 },
    ],
  },
  // 4 PHOTOS — portrait hero + 3 stacked accents on the right
  {
    id: 'hero-stack-r4',
    name: '4 · hero + stacked (R)',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 49, h: 32.5 },
      { x: 50.5, y: 33.5, w: 49, h: 32.5 },
      { x: 50.5, y: 66.5, w: 49, h: 33 },
    ],
  },
  // 5 PHOTOS — all-portrait: 2 columns left + 3 columns right
  {
    id: 'five-cols',
    name: '5 · tall columns',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24, h: 99 },
      { x: 25, y: 0.5, w: 24.5, h: 99 },
      { x: 50.5, y: 0.5, w: 16, h: 99 },
      { x: 66.83, y: 0.5, w: 16, h: 99 },
      { x: 83.17, y: 0.5, w: 16.33, h: 99 },
    ],
  },
  // 5 PHOTOS — landscape: 1 tall portrait + 4 stacked landscape bands
  {
    id: 'solo-quadband-r',
    name: '5 · solo + 4 bands',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 99, isHero: true },
      { x: 50.5, y: 0.5, w: 49, h: 24.25 },
      { x: 50.5, y: 25.25, w: 49, h: 24.25 },
      { x: 50.5, y: 50, w: 49, h: 24.25 },
      { x: 50.5, y: 75, w: 49, h: 24.5 },
    ],
  },
  // 2 PHOTOS — landscape stack on each page (good for wide photos)
  {
    id: 'duo-band',
    name: '2 · stacked bands',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 25, w: 49, h: 50 },
      { x: 50.5, y: 25, w: 49, h: 50 },
    ],
  },

  // --- MATTED / NEGATIVE-SPACE FAMILY (Phase 1a) ---
  // Slots are inset from the edges so the photo "floats" in a wide
  // mat (paper / colour / blurred-photo background fills the margin).
  // Naming: mat-<count>-<S|M|L> where S/M/L ≈ 8% / 18% / 30% margin.

  // 1 photo, centred — three mat widths
  {
    id: 'mat-1-s',
    name: 'Mat · single S',
    compat: ['standard', 'layflat'],
    slots: [{ x: 8, y: 8, w: 84, h: 84, isHero: true }],
  },
  {
    id: 'mat-1-m',
    name: 'Mat · single M',
    compat: ['standard', 'layflat'],
    slots: [{ x: 18, y: 18, w: 64, h: 64, isHero: true }],
  },
  {
    id: 'mat-1-l',
    name: 'Mat · single L',
    compat: ['standard', 'layflat'],
    slots: [{ x: 30, y: 26, w: 40, h: 48, isHero: true }],
  },
  // 1 photo, one page only — big empty facing page
  {
    id: 'mat-1-left',
    name: 'Mat · solo left, open right',
    compat: ['standard', 'layflat'],
    slots: [{ x: 6, y: 14, w: 38, h: 72, isHero: true }],
  },
  {
    id: 'mat-1-right',
    name: 'Mat · solo right, open left',
    compat: ['standard', 'layflat'],
    slots: [{ x: 56, y: 14, w: 38, h: 72, isHero: true }],
  },
  // 2 photos, matted pair (one per page, generous margins + centre gap)
  {
    id: 'mat-2',
    name: 'Mat · matted pair',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 9, y: 18, w: 33, h: 64 },
      { x: 58, y: 18, w: 33, h: 64 },
    ],
  },
  // 2 photos, offset — one large matted, one small accent + air
  {
    id: 'mat-2-offset',
    name: 'Mat · offset duo',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 8, y: 12, w: 46, h: 76, isHero: true },
      { x: 62, y: 30, w: 26, h: 40 },
    ],
  },
  // 3 photos, matted row with breathing room
  {
    id: 'mat-3',
    name: 'Mat · matted trio',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 7, y: 30, w: 26, h: 40 },
      { x: 37, y: 30, w: 26, h: 40 },
      { x: 67, y: 30, w: 26, h: 40 },
    ],
  },

  // ===== EXPANDED LIBRARY — lots more options per count =====
  // Bleed = edge-to-edge classics; mat-* = float in negative space.

  // ---- 1 PHOTO · bleed ----
  {
    id: 'one-full',
    name: '1 · full bleed',
    compat: ['standard', 'layflat'],
    slots: [{ x: 0, y: 0, w: 100, h: 100, isHero: true }],
  },

  // ---- 1 PHOTO · more mat options ----
  {
    id: 'mat-1-tall',
    name: 'Mat · tall centre',
    compat: ['standard', 'layflat'],
    slots: [{ x: 33, y: 6, w: 34, h: 88, isHero: true }],
  },
  {
    id: 'mat-1-wide',
    name: 'Mat · wide centre',
    compat: ['standard', 'layflat'],
    slots: [{ x: 12, y: 30, w: 76, h: 40, isHero: true }],
  },
  {
    id: 'mat-1-top',
    name: 'Mat · top-weighted',
    compat: ['standard', 'layflat'],
    slots: [{ x: 16, y: 8, w: 68, h: 58, isHero: true }],
  },

  // ---- 2 PHOTOS · bleed (target: lots of options) ----
  {
    id: 'b2-6040',
    name: '2 · 60 / 40',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 59, h: 99, isHero: true },
      { x: 60, y: 0.5, w: 39.5, h: 99 },
    ],
  },
  {
    id: 'b2-4060',
    name: '2 · 40 / 60',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 39, h: 99 },
      { x: 40, y: 0.5, w: 59.5, h: 99, isHero: true },
    ],
  },
  {
    id: 'b2-stack',
    name: '2 · stacked full',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 99, h: 49 },
      { x: 0.5, y: 50, w: 99, h: 49.5 },
    ],
  },
  {
    id: 'b2-stack-7030',
    name: '2 · stacked 70 / 30',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 99, h: 68, isHero: true },
      { x: 0.5, y: 69, w: 99, h: 30.5 },
    ],
  },
  {
    id: 'b2-stack-3070',
    name: '2 · stacked 30 / 70',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 99, h: 30 },
      { x: 0.5, y: 31, w: 99, h: 68.5, isHero: true },
    ],
  },
  {
    id: 'b2-left-stack',
    name: '2 · L tall + R tall (gap)',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 2, y: 2, w: 47, h: 96 },
      { x: 51, y: 2, w: 47, h: 96 },
    ],
  },
  {
    id: 'b2-center-pair',
    name: '2 · centre band pair',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 12, w: 49, h: 76 },
      { x: 50.5, y: 12, w: 49, h: 76 },
    ],
  },

  // ---- 2 PHOTOS · mat ----
  {
    id: 'mat-2-stack',
    name: 'Mat · stacked duo',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 22, y: 8, w: 56, h: 40 },
      { x: 22, y: 52, w: 56, h: 40 },
    ],
  },
  {
    id: 'mat-2-big-small',
    name: 'Mat · big + accent',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 8, y: 14, w: 52, h: 72, isHero: true },
      { x: 64, y: 34, w: 22, h: 32 },
    ],
  },
  {
    id: 'mat-2-tall',
    name: 'Mat · twin tall',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 16, y: 12, w: 28, h: 76 },
      { x: 56, y: 12, w: 28, h: 76 },
    ],
  },

  // ---- 3 PHOTOS · bleed ----
  {
    id: 'b3-row',
    name: '3 · equal columns',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 32.5, h: 99 },
      { x: 33.5, y: 0.5, w: 32.5, h: 99 },
      { x: 66.5, y: 0.5, w: 33, h: 99 },
    ],
  },
  {
    id: 'b3-stack',
    name: '3 · stacked bands',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 99, h: 32.5 },
      { x: 0.5, y: 33.5, w: 99, h: 32.5 },
      { x: 0.5, y: 66.5, w: 99, h: 33 },
    ],
  },
  {
    id: 'b3-big-top',
    name: '3 · big top + 2 below',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 99, h: 60, isHero: true },
      { x: 0.5, y: 61, w: 49, h: 38.5 },
      { x: 50.5, y: 61, w: 49, h: 38.5 },
    ],
  },
  {
    id: 'b3-2top-big',
    name: '3 · 2 top + big bottom',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 49, h: 38 },
      { x: 50.5, y: 0.5, w: 49, h: 38 },
      { x: 0.5, y: 39, w: 99, h: 60.5, isHero: true },
    ],
  },

  // ---- 3 PHOTOS · mat ----
  {
    id: 'mat-3-stack',
    name: 'Mat · stacked trio',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 30, y: 6, w: 40, h: 26 },
      { x: 30, y: 37, w: 40, h: 26 },
      { x: 30, y: 68, w: 40, h: 26 },
    ],
  },
  {
    id: 'mat-3-hero',
    name: 'Mat · hero + 2 accents',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 8, y: 14, w: 50, h: 72, isHero: true },
      { x: 64, y: 18, w: 24, h: 30 },
      { x: 64, y: 54, w: 24, h: 30 },
    ],
  },

  // ---- 4 PHOTOS · bleed ----
  {
    id: 'b4-strip',
    name: '4 · equal columns',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 24.25, h: 99 },
      { x: 25.25, y: 0.5, w: 24.25, h: 99 },
      { x: 50.5, y: 0.5, w: 24.25, h: 99 },
      { x: 75.25, y: 0.5, w: 24.25, h: 99 },
    ],
  },
  {
    id: 'b4-bands',
    name: '4 · stacked bands',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 99, h: 24.25 },
      { x: 0.5, y: 25.25, w: 99, h: 24.25 },
      { x: 0.5, y: 50, w: 99, h: 24.25 },
      { x: 0.5, y: 75, w: 99, h: 24.5 },
    ],
  },
  {
    id: 'b4-big-3',
    name: '4 · big left + 3 right bands',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 64, h: 99, isHero: true },
      { x: 65, y: 0.5, w: 34.5, h: 32.5 },
      { x: 65, y: 33.5, w: 34.5, h: 32.5 },
      { x: 65, y: 66.5, w: 34.5, h: 33 },
    ],
  },

  // ---- 4 PHOTOS · mat ----
  {
    id: 'mat-4-grid',
    name: 'Mat · 2×2 grid',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 16, y: 14, w: 32, h: 34 },
      { x: 52, y: 14, w: 32, h: 34 },
      { x: 16, y: 52, w: 32, h: 34 },
      { x: 52, y: 52, w: 32, h: 34 },
    ],
  },
  {
    id: 'mat-4-row',
    name: 'Mat · row of 4',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 6, y: 34, w: 20, h: 32 },
      { x: 29, y: 34, w: 20, h: 32 },
      { x: 52, y: 34, w: 20, h: 32 },
      { x: 75, y: 34, w: 20, h: 32 },
    ],
  },

  // ---- 5 PHOTOS · bleed ----
  {
    id: 'b5-strip',
    name: '5 · equal columns',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 19.3, h: 99 },
      { x: 20.3, y: 0.5, w: 19.3, h: 99 },
      { x: 40.1, y: 0.5, w: 19.3, h: 99 },
      { x: 59.9, y: 0.5, w: 19.3, h: 99 },
      { x: 79.7, y: 0.5, w: 19.8, h: 99 },
    ],
  },
  {
    id: 'b5-big-4',
    name: '5 · big + 4 grid',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 0.5, y: 0.5, w: 64, h: 99, isHero: true },
      { x: 65, y: 0.5, w: 17, h: 49 },
      { x: 82.5, y: 0.5, w: 17, h: 49 },
      { x: 65, y: 50, w: 17, h: 49.5 },
      { x: 82.5, y: 50, w: 17, h: 49.5 },
    ],
  },

  // ---- 5 PHOTOS · mat ----
  {
    id: 'mat-5-row',
    name: 'Mat · row of 5',
    compat: ['standard', 'layflat'],
    // 5 identical slots, evenly spaced: margin 5, gap 2.5, w 16 → ends at 95.
    slots: [
      { x: 5, y: 36, w: 16, h: 28 },
      { x: 23.5, y: 36, w: 16, h: 28 },
      { x: 42, y: 36, w: 16, h: 28 },
      { x: 60.5, y: 36, w: 16, h: 28 },
      { x: 79, y: 36, w: 16, h: 28 },
    ],
  },

  // ===== MATTED — BIGGER, VARIED COMPOSITIONS =====
  // Generous photo blocks with clean breathing room (not thin strips).

  // 1 photo
  {
    id: 'mat-1-xl',
    name: 'Mat · XL framed',
    compat: ['standard', 'layflat'],
    slots: [{ x: 6, y: 7, w: 88, h: 86, isHero: true }],
  },
  {
    id: 'mat-1-portrait-xl',
    name: 'Mat · tall XL',
    compat: ['standard', 'layflat'],
    slots: [{ x: 27, y: 5, w: 46, h: 90, isHero: true }],
  },
  {
    id: 'mat-1-band-xl',
    name: 'Mat · wide band XL',
    compat: ['standard', 'layflat'],
    slots: [{ x: 7, y: 24, w: 86, h: 52, isHero: true }],
  },

  // 2 photos — big blocks
  {
    id: 'mat-2-big',
    name: 'Mat · big pair',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 6, y: 10, w: 41, h: 80 },
      { x: 53, y: 10, w: 41, h: 80 },
    ],
  },
  {
    id: 'mat-2-big-stack',
    name: 'Mat · big stack',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 14, y: 7, w: 72, h: 40 },
      { x: 14, y: 53, w: 72, h: 40 },
    ],
  },
  {
    id: 'mat-2-Lbig-Racc',
    name: 'Mat · big left + accent',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 5, y: 8, w: 44, h: 84, isHero: true },
      { x: 55, y: 26, w: 38, h: 48 },
    ],
  },

  // 3 photos — feature + supporting
  {
    id: 'mat-3-Lbig-Rstack',
    name: 'Mat · feature + 2',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 5, y: 8, w: 46, h: 84, isHero: true },
      { x: 56, y: 8, w: 38, h: 40 },
      { x: 56, y: 52, w: 38, h: 40 },
    ],
  },
  {
    id: 'mat-3-big-row',
    name: 'Mat · big trio',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 5, y: 20, w: 28, h: 60 },
      { x: 36, y: 20, w: 28, h: 60 },
      { x: 67, y: 20, w: 28, h: 60 },
    ],
  },
  {
    id: 'mat-3-top-2big',
    name: 'Mat · banner + pair',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 8, y: 8, w: 84, h: 34 },
      { x: 8, y: 48, w: 40, h: 44 },
      { x: 52, y: 48, w: 40, h: 44 },
    ],
  },

  // 4 photos — big grid / feature
  {
    id: 'mat-4-big-grid',
    name: 'Mat · big 2×2',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 8, y: 9, w: 39, h: 39 },
      { x: 53, y: 9, w: 39, h: 39 },
      { x: 8, y: 53, w: 39, h: 39 },
      { x: 53, y: 53, w: 39, h: 39 },
    ],
  },
  {
    id: 'mat-4-Lbig-R3',
    name: 'Mat · feature + 3',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 5, y: 8, w: 46, h: 84, isHero: true },
      { x: 56, y: 8, w: 38, h: 25 },
      { x: 56, y: 37, w: 38, h: 25 },
      { x: 56, y: 67, w: 38, h: 25 },
    ],
  },

  // 5 photos — generous (replaces the tiny-row feel)
  {
    id: 'mat-5-feature',
    name: 'Mat · feature + 4',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 5, y: 9, w: 45, h: 82, isHero: true },
      { x: 54, y: 9, w: 20, h: 39 },
      { x: 76, y: 9, w: 19, h: 39 },
      { x: 54, y: 52, w: 20, h: 39 },
      { x: 76, y: 52, w: 19, h: 39 },
    ],
  },
  {
    id: 'mat-5-2top-3',
    name: 'Mat · 2 + 3 big',
    compat: ['standard', 'layflat'],
    slots: [
      { x: 13, y: 9, w: 35, h: 37 },
      { x: 52, y: 9, w: 35, h: 37 },
      { x: 7, y: 53, w: 27, h: 38 },
      { x: 37, y: 53, w: 27, h: 38 },
      { x: 67, y: 53, w: 27, h: 38 },
    ],
  },

  // --- LAYFLAT-ONLY ---
  {
    id: 'panorama',
    name: 'Panorama · full bleed',
    compat: ['layflat'],
    slots: [{ x: 0, y: 0, w: 100, h: 100, isHero: true }],
  },
  {
    id: 'hero-wide-1',
    name: 'Hero spans gutter · 1 accent',
    compat: ['layflat'],
    slots: [
      { x: 0, y: 0, w: 70, h: 100, isHero: true },
      { x: 70.5, y: 0.5, w: 29, h: 99 },
    ],
  },
  {
    id: 'hero-wide-3',
    name: 'Hero spans gutter · 3 accent',
    compat: ['layflat'],
    slots: [
      { x: 0, y: 0, w: 70, h: 100, isHero: true },
      { x: 70.5, y: 0.5, w: 29, h: 32.5 },
      { x: 70.5, y: 33.5, w: 29, h: 32.5 },
      { x: 70.5, y: 66.5, w: 29, h: 33 },
    ],
  },
]


const TEMPLATE_BY_ID = new Map(TEMPLATES.map((t) => [t.id, t] as const))

function templatesForCount(count: number, type: AlbumType): LayoutTemplate[] {
  return TEMPLATES.filter((t) => t.compat.includes(type) && t.slots.length === count)
}

// After removing a photo from a spread, pick a smaller template that
// matches the new photo count (preferring same hero/non-hero kind).
// Falls back to the closest fit if no exact match exists.
function pickFitTemplate(
  currentTplId: string,
  newCount: number,
  type: AlbumType,
): string {
  if (newCount <= 0) return currentTplId
  const current = TEMPLATE_BY_ID.get(currentTplId)
  const wantHero = current?.slots.some((s) => s.isHero) ?? false
  // Try exact-count match in same kind
  const same = TEMPLATES.find(
    (t) =>
      t.compat.includes(type) &&
      t.slots.length === newCount &&
      t.slots.some((s) => s.isHero) === wantHero,
  )
  if (same) return same.id
  // Fall back to opposite kind, exact count
  const opp = TEMPLATES.find((t) => t.compat.includes(type) && t.slots.length === newCount)
  if (opp) return opp.id
  // Last resort: keep current template id
  return currentTplId
}

export type {
  AlbumType,
  EventId,
  Slot,
  LayoutTemplate,
  Spread,
  AlbumStyle,
  LayoutFamily,
  AspectClass,
}
export {
  templateFamily,
  bleedFillSlots,
  renderSlots,
  classifyAspect,
  photoAspectClass,
  slotAspectClass,
  scoreTemplateForPhotos,
  TEMPLATES,
  TEMPLATE_BY_ID,
  templatesForCount,
  pickFitTemplate,
}
